# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerRegistryServiceConnection: 'Azure WordPress'
  imageName: 'shivisharma02/shivi-wp:latest'
  dockerRegistryCredentials: '$(DOCKER_REGISTRY_CREDENTIALS)'


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: BuildAndPushDockerImage
    displayName: 'Build and Push Docker Image'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        containerRegistry: 'Azure WordPress' # Define this as a service connection in Azure DevOps
        repository: 'Word Press'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile' # Specify the path to your Dockerfile
        tags: 'latest, $(Build.BuildId)' # You can customize the image tags here

    - task: Docker@2
      inputs:
        containerRegistry: 'Azure WordPress'
        repository: 'Word Press'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
        
