# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main  # or your preferred branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Azure WordPress'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'Azure WordPress'
    repository: 'Word Press'  # Replace with the correct repository name.
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
