trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'Azure WordPress'
  imageName: 'shivisharma02/shivi-wp'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Azure WordPress'
    repository: 'shivisharma02/shivi-wp'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'

- task: SSH@0
  inputs:
    sshEndpoint: 'Kestone_connection'
    runOptions: 'commands'
    commands: 'docker pull shivisharma02/shivi-wp;scp docker/shivisharma02/shivi-wp shivi@182.73.29.36'
    interactiveSession: true
    readyTimeout: '20000'
