# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerRegistryServiceConnection: 'Azure WordPress'
  imageName: 'shivisharma02/shivi-wp:latest'
  dockerRegistryCredentials: '$(DOCKER_REGISTRY_CREDENTIALS)'


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Azure WordPress'
        command: 'login'
    - task: Docker@2
      inputs:
        containerRegistry: 'Azure WordPress'
        repository: 'Word Press'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
