variables:
  dockerRegistryServiceConnection: 'Azure WordPress'
  imageName: 'shivisharma02/shivi-blog:latest'

trigger:
  - main  # or your preferred branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: docker build -t $(imageName) .
  displayName: 'Docker Build'
 
- script: docker push $(imageName)
  displayName: 'Docker Push'
