version: "3"
services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data_volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Allow empty password for MySQL root
      MYSQL_DATABASE: shivi-blog
    networks:
      - dockerwp

  # phpMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ""  # Empty password for MySQL root
    networks:
      - dockerwp

  # WordPress
  wordpress:
    depends_on:
      - db
    image: shivisharma02/shivi-blog-wordpress:latest
    volumes:
      - wordpress_data_volume:/var/www/html
    ports:
      - "8081:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ""
      WORDPRESS_DB_NAME: shivi-blog
    networks:
      - dockerwp

networks:
  dockerwp:

volumes:
  db_data_volume: {}
  wordpress_data_volume: {}
